### ISSUE TITLE
Module `papis-zotero.main` not found

### ISSUE THREAD

**Issue by michal-h21** [papis/papis-zotero#1]
Hi @alejandrogallo, I got this error when I tried to run `papis zotero serve`:
```

Traceback (most recent call last):
  File "/usr/local/bin/papis-zotero", line 11, in <module>
    load_entry_point('papis-zotero==0.0.1', 'console_scripts', 'papis-zotero')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/papis_zotero/__init__.py", line 6, in <module>
    import papis_zotero.server
  File "/usr/local/lib/python3.6/site-packages/papis_zotero/server.py", line 10, in <module>
    import papis_zotero.main
ModuleNotFoundError: No module named 'papis_zotero.main'

```

I've installed `papis-zotero` using:

     sudo pip3 install papis-zotero 

It seems that the file `main.py` is missing also on Github.

**Comment by alejandrogallo** [comment]
Hi @michal-h21 
it was a tiny mistake, it's fixed now, thanks for pointing it out!!

There is new a new version on pypi, as you know, simply type

```
pip3 install --upgrade papis-zotero
```

Cheers!
