### ISSUE TITLE
import problem

### ISSUE THREAD

**Issue by rhaynes74** [papis/papis-zotero#16]
Hi folks, new papis-zotero user, trying to import my library:

Traceback (most recent call last):
  File "/usr/local/bin/papis-zotero", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/papis_zotero/__init__.py", line 14, in main
    logger.info("library '{0}'".format(papis.api.get_lib()))
AttributeError: module 'papis.api' has no attribute 'get_lib'

Suggestions?

**Comment by stuartthomas25** [comment]
Looks like it's a version error. Check to see if you have version 0.0.3 or 0.1.0 as the new version works with the updated papis api. For some reason, my pip can only download 0.0.3.

**Comment by alejandrogallo** [comment]
I don't know why this would be, python version? pip version?
Are you using python3.4 or or lower ?

**Comment by stuartthomas25** [comment]
Just tried again and I'm downloading the right version. It may have been an conflict on my end.
